version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    gocyclo:
      min-complexity: 90
    goimports:
      local-prefixes: github.com/programmersd21/pyproject-tui
    govet:
      enable:
        - shadow
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
    - path: cmd/
      linters:
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0
